import type { Product } from "@/lib/types";

export const PRODUCTS: Product[] = [
  {
    id: "yakuza-lad",
    name: "Yakuza: Like a Dragon",
    brand: "SEGA",
    category: "games",
    upc: "834136006080",
    aliases: [
      "yakuza like a dragon",
      "like a dragon",
      "yakuza 7",
      "ichiban kasuga",
      "ryu ga gotoku 7",
    ],
    typical: 24.99,
    cheapShark: "yakuza like a dragon",
    alternatives: ["elden-ring", "gta5"],
    image: "/covers/yakuza.jpg",
  },
  {
    id: "palworld",
    name: "Palworld",
    brand: "Pocketpair",
    category: "games",
    upc: "1623730",
    aliases: ["palworld", "pal world", "pocketpair palworld"],
    typical: 29.99,
    cheapShark: "palworld",
    alternatives: ["elden-ring", "gta5"],
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1623730/header.jpg",
  },
  {
    id: "elden-ring",
    name: "Elden Ring",
    brand: "Bandai Namco",
    category: "games",
    upc: "722674824153",
    aliases: ["elden ring", "eldenring"],
    typical: 39.99,
    cheapShark: "elden ring",
    alternatives: ["yakuza-lad", "totk"],
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg",
  },
  {
    id: "totk",
    name: "The Legend of Zelda: Tears of the Kingdom",
    brand: "Nintendo",
    category: "games",
    upc: "045496597519",
    aliases: ["totk", "tears of the kingdom", "zelda totk"],
    typical: 54.99,
    cheapShark: "tears of the kingdom",
    alternatives: ["mario-kart", "elden-ring"],
  },
  {
    id: "gta5",
    name: "Grand Theft Auto V",
    brand: "Rockstar",
    category: "games",
    upc: "710425494507",
    aliases: ["gta 5", "gta v", "grand theft auto 5"],
    typical: 19.99,
    cheapShark: "grand theft auto v",
    alternatives: ["yakuza-lad", "elden-ring"],
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/header.jpg",
  },
  {
    id: "mario-kart",
    name: "Mario Kart 8 Deluxe",
    brand: "Nintendo",
    category: "games",
    upc: "045496420411",
    aliases: ["mario kart", "mk8"],
    typical: 49.99,
    cheapShark: "mario kart 8",
    alternatives: ["totk"],
  },
  {
    id: "chobani-greek",
    name: "Chobani Greek Yogurt, Plain 32 oz",
    brand: "Chobani",
    category: "groceries",
    upc: "818290010636",
    aliases: ["chobani", "chobani yogurt", "chobani greek yogurt", "greek yogurt"],
    typical: 5.49,
    alternatives: ["cheerios", "milk-gallon"],
  },
  {
    id: "cheerios",
    name: "Honey Nut Cheerios 18.8 oz",
    brand: "General Mills",
    category: "groceries",
    upc: "016000275287",
    aliases: ["cheerios", "honey nut cheerios"],
    typical: 4.79,
    alternatives: ["doritos", "coke-12"],
    image: "/covers/cheerios.jpg",
  },
  {
    id: "frosted-flakes",
    name: "Kellogg's Frosted Flakes",
    brand: "Kellogg's",
    category: "groceries",
    upc: "038000845217",
    aliases: ["frosted flakes", "frosted flake", "kelloggs frosted flakes", "tony the tiger"],
    typical: 4.49,
    alternatives: ["cheerios", "coke-12"],
    image: "https://world.openfoodfacts.org/images/products/003/800/084/5217/front_en.4.400.jpg",
  },
  {
    id: "coke-12",
    name: "Coca-Cola Classic 12-pack",
    brand: "Coca-Cola",
    category: "groceries",
    upc: "049000006344",
    aliases: ["coke 12 pack", "coca cola 12", "coke cans"],
    typical: 7.49,
    alternatives: ["cheerios"],
  },
  {
    id: "eggs-12",
    name: "Large Grade AA Eggs, dozen",
    brand: "Store brand",
    category: "groceries",
    upc: "070852010127",
    aliases: ["eggs", "dozen eggs"],
    typical: 3.89,
    alternatives: ["milk-gallon"],
  },
  {
    id: "milk-gallon",
    name: "Whole milk, gallon",
    brand: "Store brand",
    category: "groceries",
    upc: "011110502280",
    aliases: ["milk", "gallon of milk", "whole milk"],
    typical: 3.69,
    alternatives: ["eggs-12"],
  },
  {
    id: "avocados",
    name: "Hass avocados, bag of 4",
    brand: "Produce",
    category: "groceries",
    upc: "405338911111",
    aliases: ["avocado", "avocados", "hass avocado"],
    typical: 4.49,
    alternatives: ["bananas"],
  },
  {
    id: "bananas",
    name: "Bananas, per lb",
    brand: "Produce",
    category: "groceries",
    upc: "4011",
    aliases: ["banana", "bananas"],
    typical: 0.62,
    alternatives: ["avocados"],
  },
  {
    id: "rotisserie",
    name: "Rotisserie chicken",
    brand: "Deli",
    category: "groceries",
    upc: "211300000000",
    aliases: ["rotisserie chicken", "hot chicken"],
    typical: 7.99,
    alternatives: ["eggs-12"],
  },
  {
    id: "tide-pods",
    name: "Tide PODS Original, 42 ct",
    brand: "Tide",
    category: "home",
    upc: "037000869196",
    aliases: ["tide pods", "tidepods", "laundry pods"],
    typical: 14.97,
    alternatives: ["bounty"],
  },
  {
    id: "bounty",
    name: "Bounty paper towels, 6 giant",
    brand: "Bounty",
    category: "home",
    upc: "037000860247",
    aliases: ["bounty", "paper towels"],
    typical: 16.48,
    alternatives: ["tide-pods"],
  },
  {
    id: "doritos",
    name: "Doritos Nacho Cheese 9.25 oz",
    brand: "Frito-Lay",
    category: "groceries",
    upc: "028400089466",
    aliases: ["doritos", "nacho cheese doritos"],
    typical: 4.99,
    alternatives: ["coke-12", "cheerios"],
  },
  {
    id: "levis-501",
    name: "Levi's 501 Original Fit Jeans",
    brand: "Levi's",
    category: "clothes",
    upc: "005013334201",
    aliases: ["levis 501", "501 jeans", "levi's 501"],
    typical: 59.5,
    alternatives: ["uniqlo-tee", "nike-dunk"],
  },
  {
    id: "nike-dunk",
    name: "Nike Dunk Low Retro White/Black",
    brand: "Nike",
    category: "clothes",
    upc: "194501743519",
    aliases: ["dunk low", "panda dunks", "nike dunk"],
    typical: 115,
    alternatives: ["levis-501"],
  },
  {
    id: "uniqlo-tee",
    name: "Uniqlo Airism cotton tee",
    brand: "Uniqlo",
    category: "clothes",
    upc: "454941644201",
    aliases: ["uniqlo tee", "airism", "uniqlo tshirt"],
    typical: 14.9,
    alternatives: ["levis-501"],
  },
  {
    id: "patagonia-nano",
    name: "Patagonia Nano Puff Jacket",
    brand: "Patagonia",
    category: "clothes",
    upc: "192964504201",
    aliases: ["nano puff", "patagonia jacket"],
    typical: 199,
    alternatives: ["levis-501"],
  },
  {
    id: "airpods-pro",
    name: "Apple AirPods Pro (2nd gen, USB-C)",
    brand: "Apple",
    category: "electronics",
    upc: "195949036415",
    aliases: ["airpods pro", "airpods", "air pods pro"],
    typical: 189,
    alternatives: ["sony-xm5"],
  },
  {
    id: "sony-xm5",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "electronics",
    upc: "027242925004",
    aliases: ["xm5", "sony xm5", "wh-1000xm5"],
    typical: 298,
    alternatives: ["airpods-pro"],
  },
  {
    id: "switch-oled",
    name: "Nintendo Switch OLED",
    brand: "Nintendo",
    category: "electronics",
    upc: "045496882011",
    aliases: ["switch oled", "nintendo switch"],
    typical: 329.99,
    alternatives: ["totk", "mario-kart"],
  },
  {
    id: "advil",
    name: "Advil Ibuprofen 200mg, 100 ct",
    brand: "Advil",
    category: "pharmacy",
    upc: "305730169209",
    aliases: ["advil", "ibuprofen"],
    typical: 9.79,
    alternatives: ["nyquil", "crest"],
  },
  {
    id: "crest",
    name: "Crest 3D White toothpaste 4.1 oz",
    brand: "Crest",
    category: "pharmacy",
    upc: "037000186247",
    aliases: ["crest", "toothpaste", "3d white"],
    typical: 5.49,
    alternatives: ["advil"],
  },
  {
    id: "nyquil",
    name: "Vicks NyQuil Cold & Flu, 12 oz",
    brand: "Vicks",
    category: "pharmacy",
    upc: "323900014127",
    aliases: ["nyquil", "nyquil cold"],
    typical: 11.99,
    alternatives: ["advil"],
  },
  {
    id: "instant-pot",
    name: "Instant Pot Duo 7-in-1, 6 qt",
    brand: "Instant Pot",
    category: "home",
    upc: "810001736201",
    aliases: ["instant pot", "instantpot", "pressure cooker"],
    typical: 79.99,
    alternatives: ["bounty"],
  },
  {
    id: "armani-blazer",
    name: "Armani Collezioni wool blazer",
    brand: "Giorgio Armani",
    category: "clothes",
    upc: "360552181001",
    aliases: ["armani blazer", "armani jacket", "armani suit jacket", "giorgio armani"],
    typical: 795,
    alternatives: ["levis-501", "nano-puff-dupe"],
    image: "/covers/armani.jpg",
  },
  {
    id: "nano-puff-dupe",
    name: "Vintage quilted work jacket",
    brand: "Goodwill find",
    category: "clothes",
    upc: "000000275401",
    aliases: ["work jacket", "vintage jacket", "thrift jacket", "goodwill jacket"],
    typical: 18,
    alternatives: ["patagonia-nano", "levis-501"],
  },
  {
    id: "berserk-deluxe-1",
    name: "Berserk Deluxe Volume 1",
    brand: "Dark Horse",
    category: "books",
    upc: "9781506711980",
    aliases: [
      "berserk deluxe vol 1",
      "berserk deluxe vol. 1",
      "berserk deluxe volume 1",
      "berserk deluxe edition volume 1",
      "berserk vol 1",
      "berserk manga",
    ],
    typical: 49.99,
    alternatives: ["dune-book"],
    image: "https://covers.openlibrary.org/b/isbn/9781506711980-L.jpg",
  },
  {
    id: "atomic-habits",
    name: "Atomic Habits",
    brand: "James Clear",
    category: "books",
    upc: "9780735211292",
    aliases: ["atomic habits", "james clear"],
    typical: 18.99,
    alternatives: ["dune-book"],
    image: "https://covers.openlibrary.org/b/isbn/9780735211292-M.jpg",
  },
  {
    id: "dune-book",
    name: "Dune",
    brand: "Frank Herbert",
    category: "books",
    upc: "9780441172719",
    aliases: ["dune", "dune book", "frank herbert dune"],
    typical: 12.99,
    alternatives: ["atomic-habits"],
    image: "https://covers.openlibrary.org/b/isbn/9780441172719-M.jpg",
  },
  {
    id: "charizard-vmax",
    name: "Charizard VMAX Rainbow Rare",
    brand: "Pokémon TCG",
    category: "collectibles",
    upc: "082065080241",
    aliases: ["charizard", "charizard vmax", "pokemon charizard", "rainbow charizard"],
    typical: 189,
    alternatives: ["funko-grogu"],
  },
  {
    id: "funko-grogu",
    name: "Funko Pop Grogu with cookie",
    brand: "Funko",
    category: "collectibles",
    upc: "889698546241",
    aliases: ["grogu funko", "baby yoda funko", "funko grogu"],
    typical: 14.99,
    alternatives: ["charizard-vmax"],
  },
  {
    id: "civic-2018",
    name: "2018 Honda Civic LX",
    brand: "Honda",
    category: "cars",
    upc: "1HGCV1F30JA000001",
    aliases: ["civic", "honda civic", "2018 civic"],
    typical: 16850,
    alternatives: ["model3-used"],
  },
  {
    id: "model3-used",
    name: "2021 Tesla Model 3 Standard",
    brand: "Tesla",
    category: "cars",
    upc: "5YJ3E1EA8MF000001",
    aliases: ["model 3", "tesla model 3", "used tesla"],
    typical: 24990,
    alternatives: ["civic-2018"],
  },
  {
    id: "fenty-soft-matte",
    name: "Fenty Beauty Pro Filt'r Soft Matte foundation",
    brand: "Fenty Beauty",
    category: "beauty",
    upc: "816708021401",
    aliases: ["fenty foundation", "fenty beauty", "pro filtr", "fenty"],
    typical: 39,
    alternatives: ["rare-blush", "cerave-cream"],
    image: "/covers/fenty.jpg",
  },
  {
    id: "rare-blush",
    name: "Rare Beauty Soft Pinch liquid blush",
    brand: "Rare Beauty",
    category: "beauty",
    upc: "850033807241",
    aliases: ["rare beauty blush", "soft pinch", "rare beauty"],
    typical: 23,
    alternatives: ["fenty-soft-matte"],
  },
  {
    id: "cerave-cream",
    name: "CeraVe Moisturizing Cream 19 oz",
    brand: "CeraVe",
    category: "beauty",
    upc: "301871246201",
    aliases: ["cerave", "cerave cream", "moisturizing cream"],
    typical: 18.99,
    alternatives: ["fenty-soft-matte"],
    image: "https://images.openfoodfacts.org/images/products/030/187/124/6201/front_en.jpg",
  },
  {
    id: "lego",
    name: "LEGO",
    brand: "The LEGO Group",
    category: "home",
    upc: "",
    aliases: ["legos", "lego", "lego set", "lego bricks", "lego brick"],
    typical: 29.99,
    alternatives: ["lego-falcon", "lego-orchid"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Lego_Color_Bricks.jpg/440px-Lego_Color_Bricks.jpg",
  },
  {
    id: "lego-falcon",
    name: "LEGO Star Wars Millennium Falcon",
    brand: "LEGO",
    category: "home",
    upc: "5702015592291",
    aliases: ["millennium falcon lego", "lego falcon", "75192", "75313"],
    typical: 159.99,
    alternatives: ["lego", "lego-orchid"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Millennium_Falcon_%28LEGO%29.jpg/440px-Millennium_Falcon_%28LEGO%29.jpg",
  },
  {
    id: "lego-orchid",
    name: "LEGO Botanicals Orchid",
    brand: "LEGO",
    category: "home",
    upc: "5702017153265",
    aliases: ["lego orchid", "botanicals orchid", "10311"],
    typical: 49.99,
    alternatives: ["lego", "lego-falcon"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Lego_Color_Bricks.jpg/440px-Lego_Color_Bricks.jpg",
  },
];

export const PRODUCT_MAP = Object.fromEntries(PRODUCTS.map((p) => [p.id, p])) as Record<
  string,
  Product
>;

export const UPC_MAP = Object.fromEntries(PRODUCTS.map((p) => [p.upc, p])) as Record<
  string,
  Product
>;
